# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'answer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Answer(object):
    def setupUi(self, Answer):
        Answer.setObjectName("Answer")
        Answer.resize(870, 734)
        self.BackBtn = QtWidgets.QPushButton(Answer)
        self.BackBtn.setGeometry(QtCore.QRect(0, 0, 111, 51))
        self.BackBtn.setObjectName("BackBtn")
        self.Image_2 = QtWidgets.QLabel(Answer)
        self.Image_2.setGeometry(QtCore.QRect(260, 100, 321, 301))
        self.Image_2.setStyleSheet("QLabel {\n"
"border: 1px solid #000000\n"
"}")
        self.Image_2.setText("")
        self.Image_2.setPixmap(QtGui.QPixmap("../src/like.png"))
        self.Image_2.setScaledContents(True)
        self.Image_2.setObjectName("Image_2")
        self.CreateAnswer_2 = QtWidgets.QPushButton(Answer)
        self.CreateAnswer_2.setGeometry(QtCore.QRect(260, 510, 321, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CreateAnswer_2.setFont(font)
        self.CreateAnswer_2.setObjectName("CreateAnswer_2")
        self.Output_2 = QtWidgets.QLabel(Answer)
        self.Output_2.setGeometry(QtCore.QRect(370, 410, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Output_2.setFont(font)
        self.Output_2.setStyleSheet("QLabel{\n"
"border: 1px solid #000000\n"
"}")
        self.Output_2.setText("")
        self.Output_2.setObjectName("Output_2")

        self.retranslateUi(Answer)
        QtCore.QMetaObject.connectSlotsByName(Answer)

    def retranslateUi(self, Answer):
        _translate = QtCore.QCoreApplication.translate
        Answer.setWindowTitle(_translate("Answer", "да или нет"))
        self.BackBtn.setText(_translate("Answer", "//назад"))
        self.CreateAnswer_2.setText(_translate("Answer", "Сформировать ответ!"))


