# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cubes.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cubes(object):
    def setupUi(self, Cubes):
        Cubes.setObjectName("Cubes")
        Cubes.resize(970, 818)
        self.pushButton_back = QtWidgets.QPushButton(Cubes)
        self.pushButton_back.setGeometry(QtCore.QRect(0, 0, 161, 61))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_drop = QtWidgets.QPushButton(Cubes)
        self.pushButton_drop.setGeometry(QtCore.QRect(360, 330, 261, 51))
        self.pushButton_drop.setObjectName("pushButton_drop")
        self.Label_cube_1 = QtWidgets.QLabel(Cubes)
        self.Label_cube_1.setGeometry(QtCore.QRect(260, 410, 451, 171))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Label_cube_1.setFont(font)
        self.Label_cube_1.setStyleSheet("QLabel{\n"
"border: 1px solid black\n"
"}")
        self.Label_cube_1.setScaledContents(True)
        self.Label_cube_1.setObjectName("Label_cube_1")
        self.Output = QtWidgets.QLabel(Cubes)
        self.Output.setGeometry(QtCore.QRect(430, 620, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Output.setFont(font)
        self.Output.setStyleSheet("QLabel{\n"
"border: 1px solid black\n"
"}")
        self.Output.setText("")
        self.Output.setObjectName("Output")
        self.label = QtWidgets.QLabel(Cubes)
        self.label.setGeometry(QtCore.QRect(330, 220, 226, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Cubes)
        self.comboBox.setGeometry(QtCore.QRect(620, 220, 61, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Cubes)
        QtCore.QMetaObject.connectSlotsByName(Cubes)

    def retranslateUi(self, Cubes):
        _translate = QtCore.QCoreApplication.translate
        Cubes.setWindowTitle(_translate("Cubes", "бросить кубики"))
        self.pushButton_back.setText(_translate("Cubes", "//Назад"))
        self.pushButton_drop.setText(_translate("Cubes", "Бросить кубики!"))
        self.Label_cube_1.setText(_translate("Cubes", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Cubes", "Количество кубиков?"))
        self.comboBox.setItemText(0, _translate("Cubes", "1"))
        self.comboBox.setItemText(1, _translate("Cubes", "2"))
        self.comboBox.setItemText(2, _translate("Cubes", "3"))
        self.comboBox.setItemText(3, _translate("Cubes", "4"))
        self.comboBox.setItemText(4, _translate("Cubes", "5"))


