# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'letters.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Letters_form(object):
    def setupUi(self, Letters_form):
        Letters_form.setObjectName("Letters_form")
        Letters_form.resize(659, 707)
        self.pushButton_back = QtWidgets.QPushButton(Letters_form)
        self.pushButton_back.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_get = QtWidgets.QPushButton(Letters_form)
        self.pushButton_get.setGeometry(QtCore.QRect(210, 400, 201, 61))
        self.pushButton_get.setObjectName("pushButton_get")
        self.Output = QtWidgets.QLineEdit(Letters_form)
        self.Output.setGeometry(QtCore.QRect(270, 200, 81, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Output.setFont(font)
        self.Output.setObjectName("Output")

        self.retranslateUi(Letters_form)
        QtCore.QMetaObject.connectSlotsByName(Letters_form)

    def retranslateUi(self, Letters_form):
        _translate = QtCore.QCoreApplication.translate
        Letters_form.setWindowTitle(_translate("Letters_form", "получить букву"))
        self.pushButton_back.setText(_translate("Letters_form", "//Назад"))
        self.pushButton_get.setText(_translate("Letters_form", "Получить букву!"))
        self.Output.setText(_translate("Letters_form", "А"))



