# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(290, 60, 211, 441))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.cubes = QtWidgets.QPushButton(self.splitter)
        self.cubes.setObjectName("cubes")
        self.answer = QtWidgets.QPushButton(self.splitter)
        self.answer.setObjectName("answer")
        self.letters = QtWidgets.QPushButton(self.splitter)
        self.letters.setObjectName("letters")
        self.rules = QtWidgets.QPushButton(self.splitter)
        self.rules.setObjectName("rules")
        self.history = QtWidgets.QPushButton(self.splitter)
        self.history.setObjectName("history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рандомайзер"))
        self.cubes.setText(_translate("MainWindow", "бросить кубики"))
        self.answer.setText(_translate("MainWindow", "да или нет"))
        self.letters.setText(_translate("MainWindow", "буквы"))
        self.rules.setText(_translate("MainWindow", "правила"))
        self.history.setText(_translate("MainWindow", "история"))




